### ISSUE TITLE
tox-pyenv should not throw exception if pyenv is missing

### ISSUE THREAD

**Issue by ssbarnea** [samstav/tox-pyenv#10]
Currently if someone is installing `tox-pyenv` on a system without `pyenv` it will break any execution of `tox` with an exception like:

```
15:36:20   File "/usr/lib/python2.7/site-packages/pluggy.py", line 596, in execute
15:36:20     res = hook_impl.function(*args)
15:36:20   File "/usr/lib/python2.7/site-packages/tox_pyenv.py", line 83, in tox_get_python_executable
15:36:20     "pyenv doesn't seem to be installed, you probably "
15:36:20 tox_pyenv.PyenvMissing: pyenv doesn't seem to be installed, you probably don't want this plugin installed either.
```

Giving an warning would be ok but failing execution is clearly a big issue, especially because tox would pass otherwise.

**Comment by samstav** [comment]
@ssbarnea good point. So we don't want to raise this here:

https://github.com/samstav/tox-pyenv/blob/aad7fc16c46af0df20585719ab897a630665f700/tox_pyenv.py#L82-L84

Would you see any value/benefit to making this behavior configurable? Or should it just be changed to never fail, as you described?

**Comment by ssbarnea** [comment]
I would replace the code with `logging.warning(...)` and nothing more. If someone wants to add some extra functionality (like adding settings) this should be made as another feature.
